name: Build and Test Serial

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:    # Allows workflow to be run manually from GitHub


env:
  # Can change the CMake build type here (e.g., Release, Debug)
  BUILD_TYPE: Release

jobs:
  build-and-test-serial:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install FFTW3
      run: sudo apt-get update && sudo apt-get install -y libfftw3-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Unit Testing
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install Valgrind
      run: sudo apt-get install -y valgrind

    - name: Run Valgrind memory check
      run: |
        valgrind \
          --error-exitcode=1 \
          --track-origins=yes \
          --leak-check=full \
          --errors-for-leak-kinds=all \
          ${{github.workspace}}/build/lfts-cpu \
          ${{github.workspace}}/tests/valgrind/input_valgrind